/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.master;

import service.ServicePelanggan;
import dao.DAOPelanggan;
import tabelmodel.TableModPelanggan;
import model.ModelPelanggan;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author fuadm
 */
public class MasterPelangga extends javax.swing.JPanel {

    private ServicePelanggan servis = new DAOPelanggan();
    private TableModPelanggan tblModel = new TableModPelanggan();

    public MasterPelangga() {
        initComponents();
        tblPelanggan.setModel(tblModel);
        inputId.setVisible(true);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPelanggan = new custom.TableCustom();
        addBtn = new rojerusan.RSMaterialButtonRectangle();
        deleteBtn = new rojerusan.RSMaterialButtonRectangle();
        CancelBtn = new rojerusan.RSMaterialButtonRectangle();
        tambahPelanggan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        inputNomerHp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        saveBtn = new rojerusan.RSMaterialButtonRectangle();
        cancelBtn = new rojerusan.RSMaterialButtonRectangle();
        inputId = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(237, 233, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Data Pelanggan");

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPelanggan);

        addBtn.setText("TAMBAH");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.setText("HAPUS");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(255, 204, 51));
        CancelBtn.setText("BATAL");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tampilDataLayout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(tampilData, "card2");

        tambahPelanggan.setBackground(new java.awt.Color(237, 233, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Data Pelanggan");

        jPanel1.setBackground(new java.awt.Color(237, 233, 230));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Nama Pelanggan");

        inputNama.setBackground(new java.awt.Color(237, 233, 230));
        inputNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        inputNomerHp.setBackground(new java.awt.Color(237, 233, 230));
        inputNomerHp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Nomer HP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNama)
                    .addComponent(inputNomerHp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 759, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputNomerHp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );

        saveBtn.setText("SIMPAN");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 204, 51));
        cancelBtn.setText("BATAL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahPelangganLayout = new javax.swing.GroupLayout(tambahPelanggan);
        tambahPelanggan.setLayout(tambahPelangganLayout);
        tambahPelangganLayout.setHorizontalGroup(
            tambahPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPelangganLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(tambahPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahPelangganLayout.createSequentialGroup()
                        .addGroup(tambahPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambahPelangganLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tambahPelangganLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))))
        );
        tambahPelangganLayout.setVerticalGroup(
            tambahPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahPelangganLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tambahPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(tambahPelangganLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(inputId, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(tambahPelanggan, "card2");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(tambahPelanggan);
        MainPanel.repaint();
        MainPanel.revalidate();

        saveBtn.setText("SIMPAN");

        if (addBtn.getText().equals("UBAH")) {
            dataTabel();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        hapusData();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (saveBtn.getText().equals("TAMBAH")) {
            saveBtn.setText("SIMPAN");
        } else if (saveBtn.getText().equals("SIMPAN")) {
            simpanData();
        } else if (saveBtn.getText().equals("PERBARUI")) {
            perbaruhiData();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        if (addBtn.getText().equals("TAMBAH")) {
            addBtn.setText("UBAH");
        }
        deleteBtn.setVisible(true);
        CancelBtn.setVisible(true);
    }//GEN-LAST:event_tblPelangganMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle CancelBtn;
    private javax.swing.JPanel MainPanel;
    private rojerusan.RSMaterialButtonRectangle addBtn;
    private rojerusan.RSMaterialButtonRectangle cancelBtn;
    private rojerusan.RSMaterialButtonRectangle deleteBtn;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNomerHp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonRectangle saveBtn;
    private javax.swing.JPanel tambahPelanggan;
    private javax.swing.JPanel tampilData;
    private custom.TableCustom tblPelanggan;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        deleteBtn.setVisible(false);
        CancelBtn.setVisible(false);
        List<ModelPelanggan> list = servis.getData();
        tblModel.setData(list);
    }

    private void simpanData() {
        if (validasiInput() == true) {
            String namaPelanggan = inputNama.getText();
            String nomeHp = inputNomerHp.getText();

            ModelPelanggan mopel = new ModelPelanggan();

            mopel.setNama(namaPelanggan);
            mopel.setNoHp(nomeHp);
            servis.addData(mopel);
            tblModel.addData(mopel);
            loadData();
            resetForm();
            tampilPanel();
            saveBtn.setText("TAMBAH");
        }
    }

    private void perbaruhiData() {
        int index = tblPelanggan.getSelectedRow();
        if (index != -1) {
            ModelPelanggan mopel = tblModel.getData(tblPelanggan.convertRowIndexToModel(index));

            if (validasiInput() == true) {
                String idPelanggan = inputId.getText();
                String namaPelanggan = inputNama.getText();
                String nomeHp = inputNomerHp.getText();

                ModelPelanggan pelanggan = new ModelPelanggan();

                pelanggan.setNama(namaPelanggan);
                pelanggan.setNoHp(nomeHp);
                pelanggan.setId(idPelanggan);
                servis.UpdateData(pelanggan);
                tblModel.UpdateData(index, pelanggan);
                loadData();
                resetForm();
                tampilPanel();
                saveBtn.setText("TAMBAH");
            }
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (inputNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama pelanggan tidak boleh kosong");
        } else if (inputNomerHp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nomer telepon tidak boleh kosong");
        }else {
            valid = true;
        }
            return valid;
        }

    

    private void resetForm() {
        addBtn.requestFocus();
        addBtn.setText("TAMBAH");
        inputNama.setText("");
        inputNomerHp.setText("");
    }

    private void tampilPanel() {
        MainPanel.removeAll();
        MainPanel.add(new MasterPelangga());
        MainPanel.repaint();
        MainPanel.revalidate();
    }

    private void dataTabel() {
        tampilData.setVisible(true);
        tambahPelanggan.setVisible(true);

        int row = tblPelanggan.getSelectedRow();
        jLabel2.setText("Perbaruhi Data Kategori");

        inputId.setText(tblPelanggan.getModel().getValueAt(row, 1).toString());
        inputNama.setText(tblPelanggan.getModel().getValueAt(row, 2).toString());
        inputNomerHp.setText(tblPelanggan.getModel().getValueAt(row, 3).toString());
        aktif();
        saveBtn.setText("PERBARUI");
        cancelBtn.setVisible(true);
    }

    private void aktif() {
        inputNama.setEnabled(true);
    }

    private void hapusData() {
        int index = tblPelanggan.getSelectedRow();

        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus");
            return;
        }

        int modelRow = tblPelanggan.convertRowIndexToModel(index);

        ModelPelanggan mopel = tblModel.getData(modelRow);

        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Apakah ingin menghapus data ini?",
                "Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (confirm == JOptionPane.OK_OPTION) {
            servis.DeleteData(mopel);
            tblModel.DeleteData(index);
            loadData();
            resetForm();
        }
    }
}
