/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.master;

import dao.DAODetailTransaksi;
import service.ServiceDetailTransaksi;
import service.ServiceTransaksi;
import dao.DAOTransaksi;
import tabelmodel.TableModTransaksi;
import model.ModelProduk;
import model.ModelKategory;
import model.ModelDetailTransaksi;
import java.util.List;
import javax.swing.JOptionPane;
import model.ModelTransaksi;
import tabelmodel.TableModDetailTransaksi;
import view.datatabel.DataKategory;

/**
 *
 * @author fuadm
 */
public class Transaksi extends javax.swing.JPanel {

    private ServiceTransaksi servisTran = new DAOTransaksi();
    private ServiceDetailTransaksi servisDetTra = new DAODetailTransaksi();

    private TableModTransaksi tblModelTran = new TableModTransaksi();
    private TableModDetailTransaksi tblModelDetTran = new TableModDetailTransaksi();

    public Transaksi(String id) {
        initComponents();
        lbId.setText(id);
        tblTransaksi.setModel(tblModelTran);
        tblDetail.setModel(tblModelDetTran);
        inputId.setVisible(false);
        loadData();
        panelDetail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new custom.TableCustom();
        addBtn = new rojerusan.RSMaterialButtonRectangle();
        deleteBtn = new rojerusan.RSMaterialButtonRectangle();
        CancelBtn = new rojerusan.RSMaterialButtonRectangle();
        panelDetail = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetail = new custom.TableCustom();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        tambahKategory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inputidKategori = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputNamaKategori = new javax.swing.JTextField();
        pilihBtn = new javax.swing.JButton();
        inputNamaMenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputHarga = new javax.swing.JTextField();
        inputStok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmStatus = new javax.swing.JComboBox<>();
        saveBtn = new rojerusan.RSMaterialButtonRectangle();
        cancelBtn = new rojerusan.RSMaterialButtonRectangle();
        inputId = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(237, 233, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Data Transaksi Cafe");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        addBtn.setText("TAMBAH");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.setText("HAPUS");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(255, 204, 51));
        CancelBtn.setText("BATAL");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        panelDetail.setBackground(new java.awt.Color(237, 233, 230));

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetail);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Data Detail Transaksi Cafe");

        javax.swing.GroupLayout panelDetailLayout = new javax.swing.GroupLayout(panelDetail);
        panelDetail.setLayout(panelDetailLayout);
        panelDetailLayout.setHorizontalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(37, 37, 37))
            .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDetailLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelDetailLayout.setVerticalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDetailLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tampilDataLayout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tampilDataLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(527, 527, 527)
                        .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(tampilData, "card2");

        tambahKategory.setBackground(new java.awt.Color(237, 233, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Data Produk");

        jPanel1.setBackground(new java.awt.Color(237, 233, 230));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Jenis Kategori");

        inputidKategori.setBackground(new java.awt.Color(237, 233, 230));
        inputidKategori.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Nama Kategori");

        inputNamaKategori.setBackground(new java.awt.Color(237, 233, 230));
        inputNamaKategori.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        pilihBtn.setText("Pilih");
        pilihBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihBtnActionPerformed(evt);
            }
        });

        inputNamaMenu.setBackground(new java.awt.Color(237, 233, 230));
        inputNamaMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Nama Menu");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Harga");

        inputHarga.setBackground(new java.awt.Color(237, 233, 230));
        inputHarga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        inputStok.setBackground(new java.awt.Color(237, 233, 230));
        inputStok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Stok");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Status");

        cmStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== Pilih Status ==", "tersedia", "habis", "nonaktif", "draft", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputNamaKategori)
                    .addComponent(inputNamaMenu)
                    .addComponent(inputHarga)
                    .addComponent(inputStok)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputidKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilihBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputidKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(cmStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        saveBtn.setText("SIMPAN");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 204, 51));
        cancelBtn.setText("BATAL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahKategoryLayout = new javax.swing.GroupLayout(tambahKategory);
        tambahKategory.setLayout(tambahKategoryLayout);
        tambahKategoryLayout.setHorizontalGroup(
            tambahKategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahKategoryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(tambahKategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahKategoryLayout.createSequentialGroup()
                        .addGroup(tambahKategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambahKategoryLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(tambahKategoryLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))))
        );
        tambahKategoryLayout.setVerticalGroup(
            tambahKategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahKategoryLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tambahKategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(tambahKategoryLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(inputId, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahKategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(tambahKategory, "card2");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(tambahKategory);
        MainPanel.repaint();
        MainPanel.revalidate();

        saveBtn.setText("SIMPAN");

        if (addBtn.getText().equals("UBAH")) {
            dataTabel();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        hapusData();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (saveBtn.getText().equals("TAMBAH")) {
            saveBtn.setText("SIMPAN");
        } else if (saveBtn.getText().equals("SIMPAN")) {
            simpanData();
        } else if (saveBtn.getText().equals("PERBARUI")) {
            perbaruhiData();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        if (addBtn.getText().equals("TAMBAH")) {
            addBtn.setText("UBAH");
        }
        deleteBtn.setVisible(true);
        CancelBtn.setVisible(true);

        int row = tblTransaksi.getSelectedRow();
        String id = tblTransaksi.getValueAt(row, 0).toString();
        panelDetail.setVisible(true);
        List<ModelDetailTransaksi> list = servisDetTra.getData(id);
        tblModelDetTran.setData(list);

    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void pilihBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihBtnActionPerformed
        boolean closAble = true;
        DataKategory DKY = new DataKategory(null, closAble);
        DKY.setVisible(true);

        inputidKategori.setText(DKY.moka.getId());
        inputNamaKategori.setText(DKY.moka.getNamakategori());
        inputNamaMenu.requestFocus();
        aktif();
    }//GEN-LAST:event_pilihBtnActionPerformed

    private void tblDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDetailMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        tampilPanel();
        panelDetail.setVisible(false);
        loadData();
    }//GEN-LAST:event_jLabel9MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle CancelBtn;
    private javax.swing.JPanel MainPanel;
    private rojerusan.RSMaterialButtonRectangle addBtn;
    private rojerusan.RSMaterialButtonRectangle cancelBtn;
    private javax.swing.JComboBox<String> cmStatus;
    private rojerusan.RSMaterialButtonRectangle deleteBtn;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputNamaKategori;
    private javax.swing.JTextField inputNamaMenu;
    private javax.swing.JTextField inputStok;
    private javax.swing.JTextField inputidKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbId;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JButton pilihBtn;
    private rojerusan.RSMaterialButtonRectangle saveBtn;
    private javax.swing.JPanel tambahKategory;
    private javax.swing.JPanel tampilData;
    private custom.TableCustom tblDetail;
    private custom.TableCustom tblTransaksi;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        deleteBtn.setVisible(false);
        CancelBtn.setVisible(false);
        List<ModelTransaksi> list = servisTran.getData();
        tblModelTran.setData(list);
    }

    private void simpanData() {
        if (validasiInput() == true) {
            String jenisKategori = inputidKategori.getText();
            String jenisKategoriNama = inputNamaKategori.getText();

            String namaMenu = inputNamaMenu.getText();
            Long namaHarga = Long.parseLong(inputHarga.getText());
            int namaStok = Integer.parseInt(inputStok.getText());
            String namaStatus = cmStatus.getSelectedItem().toString();

            ModelProduk mopa = new ModelProduk();
            ModelKategory moka = new ModelKategory();

            moka.setId(jenisKategori);
            moka.setNamakategori(jenisKategoriNama);
            mopa.setNamaMenu(namaMenu);
            mopa.setHarga(namaHarga);
            mopa.setStok(namaStok);
            mopa.setStatus(namaStatus);

            mopa.setIdKategori(moka);

            servis.addData(mopa);
            tblModel.addData(mopa);
            loadData();
            resetForm();
            tampilPanel();
            saveBtn.setText("TAMBAH");
        }
    }

    private void perbaruhiData() {
        int index = tblTransaksi.getSelectedRow();
        if (index != -1) {
            ModelProduk mopa = tblModel.getData(tblTransaksi.convertRowIndexToModel(index));

            if (validasiInput() == true) {
                String jenisKategori = inputidKategori.getText();
                String jenisKategoriNama = inputNamaKategori.getText();

                String namaMenu = inputNamaMenu.getText();
                Long namaHarga = Long.parseLong(inputHarga.getText());
                int namaStok = Integer.parseInt(inputStok.getText());
                String namaStatus = cmStatus.getSelectedItem().toString();
                String idMenu = inputId.getText();

                ModelProduk mopa1 = new ModelProduk();
                ModelKategory moka = new ModelKategory();

                moka.setId(jenisKategori);
                moka.setNamakategori(jenisKategoriNama);

                mopa1.setId(idMenu);
                mopa1.setIdKategori(moka);
                mopa1.setNamaMenu(namaMenu);
                mopa1.setHarga(namaHarga);
                mopa1.setStok(namaStok);
                mopa1.setStatus(namaStatus);

                servis.UpdateData(mopa1);
                tblModel.UpdateData(index, mopa1);
                loadData();
                resetForm();
                tampilPanel();
                saveBtn.setText("TAMBAH");
            }
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (inputidKategori.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID kategori tidak boleh kosong");

        } else if (inputNamaKategori.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama kategori tidak boleh kosong");

        } else if (inputNamaMenu.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama menu tidak boleh kosong");

        } else if (inputHarga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga tidak boleh kosong");

        } else if (inputStok.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Stok tidak boleh kosong");
        } else if (cmStatus.getSelectedItem().equals("== Pilih Status ==")) {
            JOptionPane.showMessageDialog(null, "Status harus dipilih");
        } else {
            valid = true;
        }
        return valid;
    }

    private void resetForm() {
        addBtn.requestFocus();
        addBtn.setText("TAMBAH");
        inputId.setText("");
        inputidKategori.setText("");
        inputNamaKategori.setText("");
        inputNamaMenu.setText("");
        inputHarga.setText("");
        inputStok.setText("");

        cmStatus.setSelectedIndex(0);
    }

    private void tampilPanel() {
        MainPanel.removeAll();
        String id = lbId.getText();
        MainPanel.add(new Transaksi(id));
        MainPanel.repaint();
        MainPanel.revalidate();
    }

    private void dataTabel() {
        tampilData.setVisible(true);
        tambahKategory.setVisible(true);

        int row = tblTransaksi.getSelectedRow();
        jLabel2.setText("Perbaruhi Data Produk");

        inputId.setText(tblTransaksi.getModel().getValueAt(row, 1).toString());
        inputidKategori.setText(tblTransaksi.getModel().getValueAt(row, 2).toString());
        inputNamaKategori.setText(tblTransaksi.getModel().getValueAt(row, 3).toString());
        inputNamaMenu.setText(tblTransaksi.getModel().getValueAt(row, 4).toString());
        inputHarga.setText(tblTransaksi.getModel().getValueAt(row, 5).toString());
        inputStok.setText(tblTransaksi.getModel().getValueAt(row, 6).toString());
        cmStatus.setSelectedItem(tblTransaksi.getModel().getValueAt(row, 7).toString());
        aktif();
        saveBtn.setText("PERBARUI");
        cancelBtn.setVisible(true);
    }

    private void aktif() {
        inputidKategori.setEnabled(true);
        inputNamaKategori.setEnabled(true);
        inputNamaMenu.setEnabled(true);
        inputStok.setEnabled(true);
        inputHarga.setEnabled(true);
        cmStatus.setEnabled(true);
    }

    private void hapusData() {
        int index = tblTransaksi.getSelectedRow();

        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus");
            return;
        }

        int modelRow = tblTransaksi.convertRowIndexToModel(index);

        ModelTransaksi motra = tblModelTran.getData(modelRow);

        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Apakah ingin menghapus data ini?",
                "Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (confirm == JOptionPane.OK_OPTION) {
            servisTran.DeleteData(motra);
            tblModelTran.DeleteData(index);
            loadData();
            resetForm();
        }
    }
}
