/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import view.master.MasterKategory;
import view.master.MasterProduk;

/**
 *
 * @author fuadm
 */
public class MenuUtama extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtama.class.getName());

    /**
     * Creates new form DashBoard
     */
    public MenuUtama(String id, String nama, String role) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNavbar = new javax.swing.JPanel();
        pnSideBar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnMenu = new javax.swing.JPanel();
        pnContent = new javax.swing.JPanel();
        pnUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnNavbar.setBackground(new java.awt.Color(201, 153, 107));
        pnNavbar.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnNavbarLayout = new javax.swing.GroupLayout(pnNavbar);
        pnNavbar.setLayout(pnNavbarLayout);
        pnNavbarLayout.setHorizontalGroup(
            pnNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        pnNavbarLayout.setVerticalGroup(
            pnNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pnNavbar, java.awt.BorderLayout.PAGE_START);

        pnSideBar.setBackground(new java.awt.Color(237, 233, 230));
        pnSideBar.setPreferredSize(new java.awt.Dimension(250, 421));

        jScrollPane1.setBackground(new java.awt.Color(237, 233, 230));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnMenu.setBackground(new java.awt.Color(237, 233, 230));
        pnMenu.setForeground(new java.awt.Color(255, 255, 255));
        pnMenu.setLayout(new javax.swing.BoxLayout(pnMenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnMenu);

        javax.swing.GroupLayout pnSideBarLayout = new javax.swing.GroupLayout(pnSideBar);
        pnSideBar.setLayout(pnSideBarLayout);
        pnSideBarLayout.setHorizontalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSideBarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnSideBarLayout.setVerticalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSideBarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnSideBar, java.awt.BorderLayout.LINE_START);

        pnContent.setBackground(new java.awt.Color(237, 233, 230));

        pnUtama.setBackground(new java.awt.Color(237, 233, 230));
        pnUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        getContentPane().add(pnContent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(793, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pnUtama.add(new ContentBG());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuUtama("id", "nama", "role").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnNavbar;
    private javax.swing.JPanel pnSideBar;
    private javax.swing.JPanel pnUtama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        //icon
        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/img/icons8-master-20.png"));
        ImageIcon iconSecond = new ImageIcon(getClass().getResource("/img/icons8-transaction-20.png"));
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/img/icons8-transaction-list-20.png"));
        ImageIcon iconTransaksiDetail = new ImageIcon(getClass().getResource("/img/icons8-buy-with-card-20.png"));
        ImageIcon iconProduct = new ImageIcon(getClass().getResource("/img/icons8-product-20.png"));
        ImageIcon iconCategory = new ImageIcon(getClass().getResource("/img/icons8-category-20.png"));
        ImageIcon iconHome = new ImageIcon(getClass().getResource("/img/icons8-home-20.png"));

        MenuItem product = new MenuItem(null, true, iconProduct, "Product", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new MasterProduk());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem category = new MenuItem(null, true, iconCategory, "Category", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new MasterKategory());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem transaksi = new MenuItem(null, true, iconTransaksi, "Transaksi", null);
        MenuItem transaksiDetail = new MenuItem(null, true, iconTransaksiDetail, "Transaksi Detail", null);

        //List menu        
        MenuItem menuHome = new MenuItem(iconHome, false, null, "Home", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new ContentBG());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem menuMaster = new MenuItem(iconMaster, false, null, "Master", null, product, category);
        MenuItem menuTransaksi = new MenuItem(iconSecond, false, null, "Transaksi", null, transaksi, transaksiDetail);

        addMenu(menuHome, menuMaster, menuTransaksi);
    }

    private void addMenu(MenuItem... menuItems) {
        for (int i = 0; i < menuItems.length; i++) {
            pnMenu.add(menuItems[i]);
            ArrayList<MenuItem> subMenu = menuItems[i].getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }
        }
        pnMenu.revalidate();
    }

    private void setCursor() {
        pnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
}
